### ISSUE TITLE
[BUG] Compilation error on flutter beta or master: Navigator.pop(context) has type void

### ISSUE THREAD

**Issue by aam** [joshua-s/coronavirus-diary#36]
The app seems to be working fine on `stable` branch of flutter, but attempt to do `flutter run`  on `master`(8c0b43bda4e5ff29d399f06ce1c0e1027268d6b5) or `beta`(2294d75bfa8d067ba90230c0fc2268f3636d7584) gives the following compilation error:

```
[+4132 ms] 
                    Compiler message:
[        ]
../../.pub-cache/hosted/pub.dartlang.org/flutter_hud-0.2.1/lib/src/popup_hud.dar
           t:57:31: Error: This expression has type 'void' and can't be used.
[        ]   bool dismiss() => Navigator.pop(context);
[        ]                               ^
```

**Comment by dnfield** [comment]
There are breaking changes on master for the navigator - I'm not sure this should be supporting master though.

Running the develop branch on beta seems to work.

**Comment by timsneath** [comment]
Actually, I'm also struggling to get the `develop` branch to work on the current `beta` (0.15). 

```
== Building for Android ==

> /usr/local/bin/flutter build appbundle --debug
Running Gradle task 'bundleDebug'...                            


Compiler message:

../programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hud-0.2.1/lib/src/popup_hud.dart:57:31: Error: This expression has type 'void' and can't be used.

  bool dismiss() => Navigator.pop(context);

                              ^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.



FAILURE: Build failed with an exception.



* Where:

Script '/Users/builder/programs/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 833



* What went wrong:

Execution failed for task ':app:compileFlutterBuildDebug'.

> Process 'command '/Users/builder/programs/flutter/bin/flutter'' finished with non-zero exit value 1
```

**Comment by InMatrix** [comment]
I hit the same error when I was trying to run the app on beta.

**Comment by yjbanov** [comment]
This has been fixed in https://github.com/eyro-labs/flutter_hud/commit/0d5ed29fc2aa97dff2863ab824dba48264048c6a. I can send a PR to pin this repo to that version. Would that help?

**Comment by timsneath** [comment]
Good idea!

**Comment by yjbanov** [comment]
https://github.com/coronavirus-diary/coronavirus-diary/pull/53
